### ISSUE TITLE
Cannot find bower folder

### ISSUE THREAD

**Issue by mmahalwy** [martndemus/ember-cli-font-awesome#55] opened 2015-11-13 00:55 UTC
I keep getting error:

```
Cannot read property 'bowerDirectory' of undefined
TypeError: Cannot read property 'bowerDirectory' of undefined
    at Class.module.exports.treeForStyles (/home/travis/build/gadabout/kabuto/node_modules/@peekops/ember-cli-peek-ui/node_modules/ember-cli-font-awesome/index.js:35:45)
    at Class._treeFor (/home/travis/build/gadabout/kabuto/node_modules/ember-cli/lib/models/addon.js:319:31)
```

Ember-cli 1.13.12, node 5

**Comment by martndemus** [comment] 2015-11-13 15:34
@mmahalwy: I'm not able to reproduce this. If you could improve the example with more information that could help reproduce this, that would be great.

**Comment by mmahalwy** [comment] 2015-11-13 18:05
Sure, are you running on ember-cli `1.13.12` and with node 5?

**Comment by martndemus** [comment] 2015-11-13 18:47
@mmahalwy: Yes I am..

**Comment by martndemus** [comment] 2016-02-09 15:05
Closing, because I think this is not relevant anymore.

**Closed** 2016-02-09 15:05 UTC
